# Generated by Django 6.0.7 on 2026-07-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://youtube.com', help_text='YouTube channel link', null=True),
        ),
    ]
