# Generated by Django 6.0.7 on 2026-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_sitesettings_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_notification_email',
            field=models.EmailField(default='karmakar.indrajit02@gmail.com', help_text='Email address where new booking/contact inquiries are sent.', max_length=254),
        ),
    ]
