# Generated by Django 6.0.7 on 2026-07-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Royal Cinematic Package', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='e.g., 1500.00', max_digits=10)),
                ('description', models.TextField(help_text='Brief description of what is included.')),
                ('features', models.TextField(help_text='List features separated by newlines or commas.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('selected_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
