# Generated by Django 6.0.7 on 2026-08-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='cover_image',
        ),
    ]
