# Generated by Django 6.0.7 on 2026-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aarav Sharma', max_length=100)),
                ('tagline', models.CharField(default='Luxury Wedding & Cinematic Storyteller', max_length=200)),
                ('bio', models.TextField(default='Capturing timeless emotions and authentic moments with a cinematic, artistic touch.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='photographer/')),
                ('years_of_experience', models.PositiveIntegerField(default=8)),
                ('weddings_captured', models.PositiveIntegerField(default=250)),
                ('awards_won', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=250)),
                ('icon_class', models.CharField(default='fas fa-camera-retro', help_text='FontAwesome icon class, e.g., fas fa-camera-retro', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_names', models.CharField(help_text='e.g., Rhea & Vikram', max_length=150)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
    ]
