# Generated by Django 6.0.7 on 2026-07-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographerprofile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
