# Generated by Django 6.0.7 on 2026-08-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_profile_image_photographerprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
