# Generated by Django 6.0.7 on 2026-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='photographerprofile',
            name='awards_won',
        ),
        migrations.RemoveField(
            model_name='photographerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='photographerprofile',
            name='weddings_captured',
        ),
        migrations.RemoveField(
            model_name='photographerprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='bio_paragraph_1',
            field=models.TextField(default='Over the last 8 years, I have had the honor of documenting hundreds of weddings across breathtaking destinations. For me, wedding photography is not merely about posing for portraits—it is about capturing the subtle, fleeting moments that tell the true story of your day.'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='bio_paragraph_2',
            field=models.TextField(default='My aesthetic blends editorial fine-art compositions with documentary-style candid storytelling. From quiet intimate exchanges to grand cultural traditions, I ensure every memory is preserved as a timeless masterpiece.'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='countries',
            field=models.CharField(default='12+', max_length=20),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='subtitle',
            field=models.CharField(default='MY JOURNEY', max_length=100),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='title',
            field=models.CharField(default='Capturing Emotion & Legacy', max_length=200),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='weddings_shot',
            field=models.CharField(default='150+', max_length=20),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='years_experience',
            field=models.CharField(default='8+', max_length=20),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='name',
            field=models.CharField(default='Indrajeet Karmakar', max_length=100),
        ),
    ]
