# Generated by Django 6.0.7 on 2026-08-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerprofile',
            name='image',
        ),
    ]
