# Generated by Django 6.0.7 on 2026-07-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_names', models.CharField(help_text='e.g., Ananya & Rohan', max_length=150)),
                ('wedding_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(help_text='Main cover image for cards and banner', upload_to='portfolio/covers/')),
                ('short_story', models.TextField(help_text='A brief summary description of the wedding day.')),
                ('full_story', models.TextField(blank=True, help_text='Detailed narrative of the wedding celebration.', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Wedding Stories',
                'ordering': ['-wedding_date'],
            },
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.weddingstory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
